#ifndef HARDWAREPROFILE_H_INCLUDED
#define HARDWAREPROFILE_H_INCLUDED

#include <xc.h>


#define TRIS_INPUT  1
#define TRIS_OUTPUT 0


#define RELE1_LAT LATCbits.LATC2
#define RELE1_TRIS TRISCbits.TRISC2 
#define RELE2_LAT LATCbits.LATC1
#define RELE2_TRIS TRISCbits.TRISC1 
#define RELE3_LAT LATCbits.LATC0
#define RELE3_TRIS TRISCbits.TRISC0
#define RELE4_LAT LATBbits.LATB3
#define RELE4_TRIS TRISBbits.TRISB3 
#define RELE5_LAT LATBbits.LATB2
#define RELE5_TRIS TRISBbits.TRISB2 
#define RELE6_LAT LATBbits.LATB1
#define RELE6_TRIS TRISBbits.TRISB1 
#define RELE7_LAT LATBbits.LATB0
#define RELE7_TRIS TRISBbits.TRISB0 
#define RELE8_LAT LATAbits.LATA1
#define RELE8_TRIS TRISAbits.TRISA1 
#define RELE9_LAT LATAbits.LATA0
#define RELE9_TRIS TRISAbits.TRISA0
#define RELE10_LAT LATAbits.LATA12
#define RELE10_TRIS TRISAbits.TRISA12 
#define RELE11_LAT LATBbits.LATB15
#define RELE11_TRIS TRISBbits.TRISB15 
#define RELE12_LAT LATBbits.LATB14
#define RELE12_TRIS TRISBbits.TRISB14 
#define RELE13_LAT LATAbits.LATA7
#define RELE13_TRIS TRISAbits.TRISA7 
#define RELE14_LAT LATAbits.LATA10
#define RELE14_TRIS TRISAbits.TRISA10 
#define RELE15_LAT LATBbits.LATB13
#define RELE15_TRIS TRISBbits.TRISB13 
#define RELE16_LAT LATBbits.LATB12
#define RELE16_TRIS TRISBbits.TRISB12


#define DERE_LAT LATBbits.LATB6
#define DERE_TRIS TRISBbits.TRISB6
#define RX_TRIS TRISBbits.TRISB8
#define TX_TRIS TRISBbits.TRISB7


#define DIPSWITCH1_PORT (!PORTCbits.RC5)
#define DIPSWITCH1_TRIS TRISCbits.TRISC5
#define DIPSWITCH2_PORT (!PORTCbits.RC4)
#define DIPSWITCH2_TRIS TRISCbits.TRISC4


#define INPUT1_PORT PORTBbits.RB9
#define INPUT1_TRIS TRISBbits.TRISB9
#define INPUT2_PORT PORTCbits.RC6
#define INPUT2_TRIS TRISCbits.TRISC6
#define INPUT3_PORT PORTCbits.RC7
#define INPUT3_TRIS TRISCbits.TRISC7
#define INPUT4_PORT PORTCbits.RC8
#define INPUT4_TRIS TRISCbits.TRISC8
#define INPUT5_PORT PORTCbits.RC9
#define INPUT5_TRIS TRISCbits.TRISC9
#define INPUT6_PORT PORTAbits.RA11
#define INPUT6_TRIS TRISAbits.TRISA11
#define INPUT7_PORT PORTAbits.RA8
#define INPUT7_TRIS TRISAbits.TRISA8
#define INPUT8_PORT PORTAbits.RA3
#define INPUT8_TRIS TRISAbits.TRISA3
#define INPUT9_PORT PORTAbits.RA2
#define INPUT9_TRIS TRISAbits.TRISA2
#define INPUT10_PORT PORTAbits.RA13
#define INPUT10_TRIS TRISAbits.TRISA13
#define INPUT11_PORT PORTAbits.RA4
#define INPUT11_TRIS TRISAbits.TRISA4
#define INPUT12_PORT PORTBbits.RB4
#define INPUT12_TRIS TRISBbits.TRISB4


#endif